apiVersion: v1
kind: Service
metadata:
  name: acproxy-svc-test
spec:
  ports:
  - nodePort: 31369
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: acproxy
  type: NodePort
